#! /usr/bin/env python

import sys
from darkflow.cli import cliHandler

x = ['/home/ubuntu/.local/bin/flow', '--model', 'cfg/tiny-yolo-box3.cfg', '--load', 'bin/tiny-yolo-voc.weights', '--train', '--dataset', '../council/image', '--annotation', '../council/xml', '--gpu', '1.0', '--savepb', '--test', '--testImg', '/home/ubuntu/project/object_detection/council/image/',  '--testXml', '/home/ubuntu/project/object_detection/council/xml', '--threshold', '0.1']
cliHandler(x)
#x = ['/home/ubuntu/.local/bin/flow', '--pbLoad', 'built_graph/tiny-yolo-box3.pb', '--metaLoad', 'built_graph/tiny-yolo-box3.meta', '--test', '--testImg', '/home/ubuntu/project/object_detection/council/image/',  '--testXml', '/home/ubuntu/project/object_detection/council/xml', '--threshold', '0.1', '--gpu', '1.0']
#cliHandler(x)
print('ok')
#cliHandler(sys.argv)
