#! /usr/bin/env python
import os
import json
import sys
from darkflow.cli import cliHandler

with open('parameter/parameter.json') as json_file:
    data = json.load(json_file)
x = ['/home/ubuntu/.local/bin/flow','--model', data['model'],  '--load', data['load'], '--train', data['train'], '--dataset', data['dataset'], '--annotation', data['annotation'], '--gpu', data['gpu'], '--savepb', data['savepb'],'--test', data['test'],'--testImg', data['testImg'],  '--testXml', data['testXml'], '--threshold', data['threshold'], '--epoch', data['epoch'], '--labels', data['labels'], '--testThreshold', data['testThreshold']]
cliHandler(x)
#cliHandler(x)
#cliHandler(sys.argv)
